# -*- coding: utf-8 -*-
"""b2_Sentiment_Predictor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hE3Mnf4mRFiJOvpRszGd1Hk1MAuf2z6J

###Importing libraries
"""

import numpy as np
import pandas as pd

"""###Importing dataset (from google drive)"""

from google.colab import drive
drive.mount('/content/drive')

dataset = pd.read_csv('./drive/My Drive/Project2_Sentiment_Analysis/a2_RestaurantReviews_FreshDump.tsv', delimiter = '\t', quoting = 3)
dataset.head()

"""###Data cleaning"""

import re
import nltk

nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

all_stopwords = stopwords.words('english')
all_stopwords.remove('not')

corpus=[]

for i in range(0, 100):
  review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

"""###Data transformation"""

# Loading BoW dictionary
from sklearn.feature_extraction.text import CountVectorizer
import pickle
cvFile='./drive/MyDrive/Project2_Sentiment_Analysis/c1_BoW_Sentiment_Model.pkl'
# cv = CountVectorizer(decode_error="replace", vocabulary=pickle.load(open('./drive/MyDrive/Colab Notebooks/2 Sentiment Analysis (Basic)/3.1 BoW_Sentiment Model.pkl', "rb")))
cv = pickle.load(open(cvFile, "rb"))

X_fresh = cv.transform(corpus).toarray()
X_fresh.shape

"""###Predictions (via sentiment classifier)"""

import joblib
classifier = joblib.load('./drive/MyDrive/Project2_Sentiment_Analysis/c2_Classifier_Sentiment_Model')

y_pred = classifier.predict(X_fresh)
print(y_pred)

dataset['predicted_label'] = y_pred.tolist()
dataset.head()

dataset.to_csv("./drive/MyDrive/Project2_Sentiment_Analysis/c3_Predicted_Sentiments_Fresh_Dump.tsv", sep='\t', encoding='UTF-8', index=False)